### ISSUE TITLE
CUDA_HOME environment variable is not set.

### ISSUE THREAD

**Issue by dataprolet** [rocm-arch/python-torchvision-rocm#10]
Installation of this package fails on my system due to the CUDA_HOME environment variable not being set. I don't understand why this needs a CUDA environment variable, when it's specifically for AMD.

```
[100%] Built target torchvision
No ROCm runtime is found, using ROCM_HOME='/opt/rocm/'
Building wheel torchvision-0.15.1a0+69fc115
Compiling extensions with following flags:
  FORCE_CUDA: True
  DEBUG: False
  TORCHVISION_USE_PNG: True
  TORCHVISION_USE_JPEG: True
  TORCHVISION_USE_NVJPEG: False
  TORCHVISION_USE_FFMPEG: True
  TORCHVISION_USE_VIDEO_CODEC: False
  NVCC_FLAGS: 
Traceback (most recent call last):
  File "/home/$user/.build/python-torchvision-rocm/src/vision-0.15.1/setup.py", line 544, in <module>
    ext_modules=get_extensions(),
                ^^^^^^^^^^^^^^^^
  File "/home/$user/.build/python-torchvision-rocm/src/vision-0.15.1/setup.py", line 227, in get_extensions
    extension(
  File "/home/$user/.local/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1048, in CUDAExtension
    library_dirs += library_paths(cuda=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$user/.local/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$user/.local/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2223, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by arch-btw** [comment]
Getting the same error. I'm wondering if this line is causing it in the PKGBUILD?


>  FORCE_CUDA=1 \


https://github.com/rocm-arch/python-torchvision-rocm/blob/69fc11591ec60f310dc0dda4788075c9111c4a48/PKGBUILD#LL88C1-L88C14

**Comment by wuxxin** [comment]
@dataprolet , @arch-btw  thank you for investigating, fixed in 0.15.1 (4)

**Comment by arch-btw** [comment]
Thank you @wuxxin !

**Comment by dataprolet** [comment]
Thanks for the fast fix!
