### ISSUE TITLE
Doesn't compile due to CUDA version

### ISSUE THREAD

**Issue by binarydepth** [rocm-arch/python-torchvision-rocm#2]
I am totally new to CUDA and ROCm. I downloaded the PKGBUILD to troubelshoot

running build_ext
Traceback (most recent call last):
File "/home/binarydepth/.cache/paru/clone/python-torchvision-rocm/src/vision-0.13.1/setup.py", line 514, in <module>
setup(
File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
return run_commands(dist)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
dist.run_commands()
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
super().run_command(command)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
super().run_command(command)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
_build_ext.run(self)
File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
self.build_extensions()
File "/home/binarydepth/.local/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
self._check_cuda_version(compiler_name, compiler_version)
File "/home/binarydepth/.local/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (11.7) mismatches the version that was used to compile
PyTorch (10.2). Please make sure to use the same CUDA versions.

Is my GPU incompatible? RX 590 or is it some CUDA requirements to build?

**Comment by wuxxin** [comment]
hey, your problem is probably somewhere else. :no_good: 

- you are using an local custom build python, that's older than the python on arch
- this package needs python-pytorch-rocm as base package
- this needs the rocm stack build beforehand 

Some hints for you:  

- use the buildin python
- build the newest rocm stack: rocm-hip-sdk roctracer miopen hipmagma rocminfo
- build python-pytorch-rocm
- then build this package
 
if you succeed in all of the above :+1: 
and python-torchvision still throws a build error, please open a new ticket with:
- output of `rocminfo`
- output of the build

**Comment by wuxxin** [comment]
i think arch4edu works again, but the buildlog suggests that you are using a local python build with a local pytorch (maybe from pypi) which are both not connected to the arch4edu packages

**Comment by wuxxin** [comment]
on arch/manjaro, don't install systemwide packages via pip, and for packages python-pytorch-rocm and other *-rocm packages on arch you need to use the system python. Maybe this is related to older arch4edu packages, and other user environments, uninstall everything rocm related, all user environments related and start fresh. once rocminfo is running, you're are on the right path

**Comment by acxz** [comment]
Since this seems to be a support issue rather than a core build issue, you can open up a discussion post over at https://github.com/rocm-arch/rocm-arch/discussions, @binarydepth
