### ISSUE TITLE
After update 0.16.2-1 cant compile (libmkl_intel_lp64.so.2)

### ISSUE THREAD

**Issue by Sosiaka** [rocm-arch/python-torchvision-rocm#20]
```cpp
cc1plus: предупреждение: command-line option «-Wno-duplicate-decl-specifier» is valid for C/ObjC but not for C++
In file included from /home/sosiska/.cache/paru/clone/python-torchvision-rocm/src/vision-0.16.2/torchvision/csrc/vision.cpp:1:
/home/sosiska/.cache/paru/clone/python-torchvision-rocm/src/vision-0.16.2/torchvision/csrc/vision.h:10:40: предупреждение: «extern» декларация «_register_ops» с инициализацией
   10 | extern "C" VISION_INLINE_VARIABLE auto _register_ops = &cuda_version;
      |                                        ^~~~~~~~~~~~~
[100%] Linking CXX shared library libtorchvision.so
[100%] Built target torchvision
Traceback (most recent call last):
  File "/home/sosiska/.cache/paru/clone/python-torchvision-rocm/src/vision-0.16.2/setup.py", line 9, in <module>
    import torch
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 193, in _load_global_deps
    raise err
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
ошибка: не удалось собрать «python-torchvision-rocm-0.16.2-1»:
ошибка: не удалось собрать пакеты: python-torchvision-rocm-0.16.2-1
```
Installed cuda, it doesnt help

**Comment by wuxxin** [comment]
did you try to `python -c "import torch` to see if you pytorch is working ?

**Comment by Sosiaka** [comment]
Same error :(

**Comment by Sosiaka** [comment]
About "same error"

It says that I don't have gpu. When I add ignore flag to my program, it gives this error

**Comment by Sosiaka** [comment]
My system info
```bash
~ /opt/rocm/bin/rocminfo | grep -E "(Name|ID):"
export | grep -E "(GPU_TARGETS|AMDGPU_TARGETS|PYTORCH_ROCM_ARCH|HSA_OVERRIDE_GFX_VERSION)"
  Name:                    AMD Ryzen 5 3600X 6-Core Processor
  Marketing Name:          AMD Ryzen 5 3600X 6-Core Processor
  Vendor Name:             CPU
  Chip ID:                 0(0x0)
  BDFID:                   0
  Internal Node ID:        0
  Name:                    gfx1030
  Marketing Name:          AMD Radeon RX 6900 XT
  Vendor Name:             AMD
  Chip ID:                 29631(0x73bf)
  BDFID:                   2560
  Internal Node ID:        1
      Name:                    amdgcn-amd-amdhsa--gfx1030
      ```

**Comment by Sosiaka** [comment]
Can u give me previous version pls?

**Comment by Sosiaka** [comment]
Used previous version with same result:
```bash
[100%] Linking CXX shared library libtorchvision.so
[100%] Built target torchvision
Traceback (most recent call last):
  File "/home/sosiska/bebra/src/vision-0.16.1/setup.py", line 9, in <module>
    import torch
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 193, in _load_global_deps
    raise err
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
```

**Comment by wuxxin** [comment]
your pytorch packet is broken,
and building torch-vision requires a running pytorch.

if python -c "import torch" does not work it is not related to torch-vision
Try to reinstall python-pytorch version 2.1.1, maybe this works for you.

vision 16.1 needs pytorch 2.1.1 , vision 16.2 need pytorch 2.1.2

you could open a bug for python-pytorch-rocm but your error is not related to pytorch-vision.

**Comment by Sosiaka** [comment]
```bash
   bebra sudo pacman -U file:///home/sosiska/python-pytorch-rocm-2.1.0-1-x86_64.pkg.tar.zst
:: Получение пакетов...
 python-pytorch-rocm-2.1.0-1-x86_64                                                                                         155,9 MiB  1367 MiB/s 00:00 [#############################################################################################] 100%
загрузка пакетов...
предупреждение: откат версии пакета python-pytorch-rocm (2.1.1-2 => 2.1.0-1)
разрешение зависимостей...
проверка конфликтов...

Пакеты (1) python-pytorch-rocm-2.1.0-1

Будет установлено:  1928,91 MiB
Изменение размера:    -0,03 MiB

:: Приступить к установке? [Y/n]
(1/1) проверка ключей                                                                                                                                   [#############################################################################################] 100%
(1/1) проверка целостности пакета                                                                                                                       [#############################################################################################] 100%
(1/1) загрузка файлов пакетов                                                                                                                           [#############################################################################################] 100%
(1/1) проверка конфликтов файлов                                                                                                                        [#############################################################################################] 100%
(1/1) проверка доступного места                                                                                                                         [#############################################################################################] 100%
:: Обработка изменений пакета...
(1/1) откат версии python-pytorch-rocm                                                                                                                  [#############################################################################################] 100%
:: Запуск post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating executables in /usr/bin...
   bebra python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 193, in _load_global_deps
    raise err
  File "/usr/lib/python3.11/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```
It doesnt help

**Comment by Sosiaka** [comment]
https://github.com/pytorch/xla/issues/1666

**If someone has same problem**
