### ISSUE TITLE
‘TORCH_CHECK_EQ’ was not declared in this scope; did you mean ‘TORCH_CHECK_MSG’

### ISSUE THREAD

**Issue by thorjelly** [rocm-arch/python-torchvision-rocm#9]
```
FAILED: /home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/build/temp.linux-x86_64-cpython-310/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.o 
c++ -MMD -MF /home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/build/temp.linux-x86_64-cpython-310/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/decoder -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video_reader -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc -I/usr/include/ffmpeg4.4 -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/TH -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/THC -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/THH -I/opt/rocm/include -I/opt/rocm/miopen/include -I/opt/rocm/hip/include -I/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/TH -I/home/thorjelly/.local/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -c -c /home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.cpp -o /home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/build/temp.linux-x86_64-cpython-310/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.o -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=video_reader -D_GLIBCXX_USE_CXX11_ABI=0
/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.cpp: In member function ‘std::tuple<at::Tensor, double> vision::video::Video::Next()’:
/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/torchvision/csrc/io/video/video.cpp:355:7: error: ‘TORCH_CHECK_EQ’ was not declared in this scope; did you mean ‘TORCH_CHECK_MSG’?
  355 |       TORCH_CHECK_EQ(frameSizeTotal % (outAudioChannels * bytesPerSample), 0);
      |       ^~~~~~~~~~~~~~
      |       TORCH_CHECK_MSG
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/thorjelly/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thorjelly/.cache/paru/clone/python-torchvision-rocm/src/vision-0.15.1/setup.py", line 526, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/thorjelly/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/thorjelly/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/thorjelly/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/thorjelly/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Is this an incompatibility with `python-pytorch-rocm 2.0.0`? If so, how could I use an older version?

**Comment by wuxxin** [comment]
was due to 2.0.0, and old vision, as vision is updated to 0.15.1 this should work now.
